newsuk/times-components-native

- .github/semantic.yml
> Allowed types can be found at https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json
> chore: Configuration for Semantic Pull Requests

- package.json
- scrollbars on tablet article page
- `article-comment-tablet` ui changes.
> chore: Release v1.1.11

- package.json
> chore: release v1.1.12

- package.json
> chore: release - 1.1.13

- packages/article-skeleton/src/article-body/article-body-row.js
- hide ads on `magazinecomment` template on tablet.
> chore: temp hide ads on magazinecomment articles on tablet

- packages/edition-slices/src/edition-slices.js
- Map 3 new slices to existing slices while we develop our new `TopSecondaryFourSlice`
- Allows TPA to release ahead of apps without issue.
> chore: map new top secondary slices

- packages/provider-queries/src/section_fragment.graphql
> fix: corrects graphql schema type

- package.json
> chore: release 1.1.14

- app/index.ts
- app/storybook/index.js
- ios/Podfile.lock
- package.json
- yarn.lock
Creates a separate navigation stack that only has a single view that's "Storybook".
> chore: Improve dev experience - remember selected story

- packages/article-skeleton/src/article-body/inline-paragraph.js
Not much more to say (other than I also fixed the inline paragraph width).
> feat: Right align mpu ads

- package.json
Bumping the minor version as graphql query has changed
> chore: release 1.3.0

- packages/edition-slices/index.js
- packages/edition-slices/src/edition-slices.js
- packages/section/__tests__/android/__snapshots__/section.test.js.snap
- packages/section/__tests__/ios/__snapshots__/section.test.js.snap
- packages/section/__tests__/shared.js
- packages/section/__tests__/unit/utils.test.js
- packages/section/src/section.js
- packages/section/src/slice.js
- packages/section/src/utils.js
- provide a temporary way to identify is a slice is within a supplement section.
> feat: Supplement section logic

- packages/section/src/utils.js
> fix: supplement titles

- package.json
- releases latest front page grid changes and ad title for MPUs
> chore: release 1.7.0

- lib/android/modulePaths.js
- packages/article-skeleton/__tests__/body-utils.native.js
- packages/article-skeleton/src/body-utils.js
- yarn.lock
https://nidigitalsolutions.jira.com/browse/TNLT-4684
**Before:**
**After:**
PS: Added `Dimensions` to our `modulePaths` as it was missing.
> fix: Removes inline image if it is the first item in the article content

- packages/article-byline/__tests__/android/__snapshots__/article-byline-opinion-style.android.test.js.snap
- packages/article-byline/__tests__/android/__snapshots__/article-byline-opinion.android.test.js.snap
- packages/article-byline/__tests__/android/__snapshots__/article-byline-style.android.test.js.snap
- packages/article-byline/__tests__/android/__snapshots__/article-byline-with-links-style.android.test.js.snap
- packages/article-byline/__tests__/android/__snapshots__/article-byline-with-links.android.test.js.snap
- packages/article-byline/__tests__/android/__snapshots__/article-byline.android.test.js.snap
- packages/article-byline/__tests__/ios/__snapshots__/article-byline-opinion-style.ios.test.js.snap
- packages/article-byline/__tests__/ios/__snapshots__/article-byline-opinion.ios.test.js.snap
- packages/article-byline/__tests__/ios/__snapshots__/article-byline-style.ios.test.js.snap
- packages/article-byline/__tests__/ios/__snapshots__/article-byline-with-links-style.ios.test.js.snap
- packages/article-byline/__tests__/ios/__snapshots__/article-byline-with-links.ios.test.js.snap
- packages/article-byline/__tests__/ios/__snapshots__/article-byline.ios.test.js.snap
- packages/article-byline/__tests__/shared.base.js
- packages/article-byline/src/render-byline.js
- packages/edition-slices/__tests__/android/__snapshots__/tile-h.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tile-p.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tile-h.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tile-p.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std-has-video.android.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std-with-style.android.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std.android-1article.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std.android-2articles.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std.android-3articles.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std.android-no-short-headline.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-1article.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-2articles.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-3articles.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-has-video.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-no-short-headline.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-with-style.ios.test.js.snap
https://nidigitalsolutions.jira.com/browse/TNLT-4716
We need to wrap byline in a Text component, which ensures that the nested Text components wrap to multiple lines as expected. 
**Before:**
**After:**
> fix(TNLT-4716): Fixes byline text wrapping

- packages/edition-slices/src/tiles/shared/positioned-tile-star.js
- packages/section/__tests__/shared-tracking.js
https://nidigitalsolutions.jira.com/browse/TNLT-4855
> feat(TNLT-4855): Hide save star on tablet

- package.json
> chore: Release v1.8.0

- packages/article-skeleton/src/article-body/article-body-row.js
- only shows ads on tablet on article using `mainstandard` template
- https://nidigitalsolutions.jira.com/browse/TNLT-4756
> feat: (TNLT-4756) Only shows ads on tablet on mainstandard template

- CODEOWNERS
> chore: Update codeowners 😢  👋

- packages/article-skeleton/__tests__/android/__snapshots__/article-header-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article-images.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-header-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-images.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/src/article-skeleton.js
- https://nidigitalsolutions.jira.com/browse/TNLT-5098
- Enable vertical scrollbars on mobile article pages
- `showsVerticalScrollIndicator` defaults to `true`
> chore: (TNLT-5098) Enable vertical scrollbars on mobile article pages

- ios/Podfile.lock
> chore: updates Podfile.lock

- packages/article-skeleton/fixtures/full-article-content.js
- packages/article-skeleton/src/article-body/article-body-row.js
> fix(TNLT-4833): renders unknown AST correctly

- packages/section/src/utils.js
- https://nidigitalsolutions.jira.com/browse/TNLT-5144
- https://nidigitalsolutions.jira.com/browse/TNLT-5143
> chore: Add two more sections to known supplement list

- packages/article-skeleton/__tests__/android/__snapshots__/newsletter-puff-button.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/newsletter-puff-link.test.js.snap
- packages/article-skeleton/__tests__/inline-newsletter-puff.base.js
- packages/article-skeleton/__tests__/ios/__snapshots__/newsletter-puff-button.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/newsletter-puff-link.test.js.snap
- packages/article-skeleton/__tests__/newsletter-puff-button.base.js
- packages/article-skeleton/__tests__/newsletter-puff-link.base.js
- packages/article-skeleton/src/article-body/inline-newsletter-puff.js
- packages/article-skeleton/src/article-body/newsletter-puff-button.js
- packages/article-skeleton/src/article-body/newsletter-puff-link.js
- packages/provider-queries/src/get_newsletter.graphql
In this PR we update the tracking for NewsletterPuff. You can find the specs [here](https://docs.google.com/spreadsheets/d/1NVWE4VxOB0hUkUBgmOmOoC_G0qoAQr0T/edit#gid=152412066) in the columns BO12, BP12 and BQ12
[TNLT-4872](https://nidigitalsolutions.jira.com/browse/TNLT-4872)
PR [#2647](https://github.com/newsuk/times-components/pull/2647) in `times-components`
> fix(TNLT-4872): Update NewsletterPuff tracking

- package.json
> chore: release v1.10.0

- packages/article-byline/src/article-byline-prop-types.js
- packages/article-extras/src/article-extras-content.js
- packages/article-extras/src/article-topics/index.js
- packages/article-image/src/article-image.base.js
- packages/article-image/src/article-image.js
- packages/article-image/src/inset-caption.js
- packages/article-main-comment/src/article-header/article-header.js
- packages/article-paragraph/src/article-paragraph.js
- packages/article-paragraph/src/drop-cap.js
- packages/article-skeleton/src/article-topics/index.js
- packages/edition-slices/src/slices/shared/flush-responsive-slice.js
- packages/edition-slices/src/slices/shared/gutter.js
- packages/edition-slices/src/slices/shared/responsive-slice.js
- packages/edition-slices/src/slices/supplementleadoneandfour/index.js
- packages/key-facts/src/key-facts-container.js
- packages/key-facts/src/key-facts-title.js
- packages/section/src/magazine-cover.js
> chore: Context changes to use hook where possible

- packages/article-skeleton/src/article-body/inline-paragraph.js
https://nidigitalsolutions.jira.com/browse/TNLT-5245
> fix: Make MPU inline ads clickable

- packages/article-skeleton/src/article-body/article-body-row.js
https://nidigitalsolutions.jira.com/browse/TNLT-5159
Default view of Responsive Graphic Interactive (fixed)
As above with `display: "fullwidth"` prop set
> fix: interactives

- package.json
> chore: release v1.10.1

- package.json
> chore: Release v1.10.2

- package.json
> chore: Release v1.10.3

- packages/styleguide/__tests__/breakpoints/index.test.js
- packages/styleguide/src/breakpoints/index.js
- packages/styleguide/src/styleguide.js
> chore: Adds device style util

- packages/edition-slices/__tests__/android/__snapshots__/tile-f-front.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tile-f-front.test.js.snap
- packages/edition-slices/src/tiles/tile-f-front/styles/index.js
> fix: updates standfirst colour/size for front lead1

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/shared-tablet-slices.base.js
- packages/edition-slices/src/slices/leadtwonopicandtwo/index.js
- packages/slice-layout/__tests__/android/__snapshots__/l2np2-with-style.android.test.js.snap
- packages/slice-layout/__tests__/android/__snapshots__/l2np2.android.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/l2np2-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/l2np2.ios.test.js.snap
- packages/slice-layout/__tests__/l2np2.base.js
- packages/slice-layout/src/templates/leadtwonopicandtwo/index.js
- packages/slice-layout/src/templates/leadtwonopicandtwo/styles.js
https://nidigitalsolutions.jira.com/browse/TNLT-5160
**Mobile**
___
**iPad 7 (medium)**
___
**iPad Pro 12.9**
> fix(TNLT-5160): fixes lead2nopicand2 on wide portrait

- package.json
> chore: release v1.10.5

- packages/article-skeleton/__tests__/android/__snapshots__/inline-newsletter-puff.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/inline-newsletter-puff.test.js.snap
- packages/article-skeleton/src/article-body/inline-newsletter-puff.js
- packages/article-skeleton/src/styles/inline-newsletter-puff.js
In this PR we change the copy that is displayed when a user sign up successfully to a newsletter
[TNLT-5506](https://nidigitalsolutions.jira.com/browse/TNLT-5506)
PR [#2649](https://github.com/newsuk/times-components/pull/2649) in `times-components`
> feat(TNLT-5506): Change confirmation copy in newsletter puff

- package.json
> chore: Release v1.10.6

- package.json
> chore: Release v1.10.7

- packages/edition-slices/edition-front.showcase.js
> fix: fixes Fronts stories on android

- package.json
Releases :
- Integrated fronts 
- Front layout improvements
> chore: release 1.11.0

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tile-g-front.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tile-h-front.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tile-g-front.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tile-h-front.test.js.snap
- packages/edition-slices/src/tiles/tile-g-front/styles/index.js
- packages/edition-slices/src/tiles/tile-h-front/styles/index.js
- packages/slice-layout/__tests__/android/__snapshots__/front-l2-with-style.android.test.js.snap
- packages/slice-layout/__tests__/android/__snapshots__/front-l2.android.test.js.snap
- packages/slice-layout/__tests__/front-l2.base.js
- packages/slice-layout/__tests__/ios/__snapshots__/front-l2-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/front-l2.ios.test.js.snap
- packages/slice-layout/src/templates/frontleadtwo/index.js
- packages/slice-layout/src/templates/frontleadtwo/styles.js
https://nidigitalsolutions.jira.com/browse/TNLT-5499
**iPad Air 3**
___
**iPad Pro 12.9''**
___
**iPad Pro 11''**
> fix(TNLT-5499): factor in home bar on front lead two

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/src/slices/frontleadone/index.js
- packages/edition-slices/src/tiles/tile-f-front/index.js
- Fixes styling issues on `LeadOneFront`
> fix: Lead one styling issue

- packages/slice-layout/__tests__/android/__snapshots__/front-l2-with-style.android.test.js.snap
- packages/slice-layout/__tests__/android/__snapshots__/front-l2.android.test.js.snap
- packages/slice-layout/src/templates/frontleadtwo/styles.android.js
> fix: fixes android front lead 2

- package.json
- Fix to lead one front slice styling
> chore: release v1.11.1

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tile-f-front.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tile-f-front.test.js.snap
- packages/edition-slices/src/tiles/tile-f-front/styles/index.js
- packages/slice-layout/src/templates/frontleadone/styles.js
https://nidigitalsolutions.jira.com/browse/TNLT-5499
**iPad AIr 3**
___
**iPad Pro 11''**
___
**iPad Pro 12.9''''**
> fix(TNLT-5499): factors in home-bar on front lead1

- packages/edition-slices/__tests__/android/__snapshots__/tile-a-front.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tile-a-front.test.js.snap
- packages/edition-slices/src/tiles/tile-a-front/index.js
- Amend tile a front to only show 2 cols of text
> feat: Amend tile a front to only show 2 cols of text

- packages/in-todays-edition/__tests__/android/__snapshots__/shared.test.js.snap
- packages/in-todays-edition/__tests__/ios/__snapshots__/shared.test.js.snap
- packages/in-todays-edition/styles/index.js
- align ITE item CTA text to bottom
> fix: Align ITE item CTA text to bottom

- packages/front-page/__tests__/__snapshots__/front-page-byline.test.tsx.snap
- packages/front-page/front-page-byline/styles.ts
> fix: aligns byline to body copy

- package.json
- Release new param on section page `onArticlePress` callback
> chore: release v1.11.2

- package.json
- Perf improvement to inline ads
- Fix various front layout issues
> chore: release v1.11.3

- packages/in-todays-edition/__tests__/android/__snapshots__/shared.test.js.snap
- packages/in-todays-edition/__tests__/ios/__snapshots__/shared.test.js.snap
- packages/in-todays-edition/item.tsx
- packages/in-todays-edition/styles/index.js
- Remove CTA on `InTheEdition` items in portrait
> fix: remove ITE CTA on portrait

- packages/front-page/__tests__/__snapshots__/front-tile-summary.test.js.snap
- packages/front-page/__tests__/front-article-summary-content.test.js
- packages/front-page/__tests__/get-front-tile-config.test.ts
- packages/front-page/front-article-summary-content/index.tsx
- packages/front-page/front-tile-summary.tsx
- packages/front-page/utils/get-front-tile-config.ts
- packages/section/src/section.js
> fix: only renders allowed number of teaser text lines

- package.json
> chore: release v1.11.5

- package.json
- Various front layout improvements and fixes.
> chore: release v1.11.6

- packages/article-columns/__tests__/measure/__snapshots__/MeasureComponents.test.tsx.snap
- packages/article-columns/__tests__/render/__snapshots__/Columns.test.tsx.snap
- packages/article-summary/src/article-summary-headline.js
- packages/article-summary/src/article-summary-strapline.js
- packages/front-page/__tests__/__snapshots__/front-article-summary-content.test.js.snap
- packages/front-page/__tests__/__snapshots__/front-page-byline.test.tsx.snap
- packages/front-page/__tests__/__snapshots__/front-renderer.test.js.snap
- packages/front-page/__tests__/__snapshots__/front-tile-summary.test.js.snap
- packages/front-page/front-article-summary-content/index.tsx
- packages/front-page/front-page-byline/index.tsx
- packages/front-page/front-renderer.tsx
- packages/front-page/front-tile-summary.tsx
- packages/in-todays-edition/in-todays-edition.tsx
- packages/in-todays-edition/item.tsx
> fix: ignores system font size on front

- CODEOWNERS
- package.json
> chore: 1.11.7

- packages/ad/__tests__/android/__snapshots__/ad-with-style.android.test.js.snap
- packages/ad/__tests__/ios/__snapshots__/ad-with-style.ios.test.js.snap
- packages/ad/src/ad.js
- packages/ad/src/dom-context.js
- packages/section/__tests__/unit/utils.test.js
- packages/section/src/utils.js
> fix: renders ads with initial height

- package.json
> chore: release v1.11.9

- packages/author-profile/__tests__/shared-with-style.native.js
- packages/author-profile/src/author-profile-prop-types.base.js
- packages/author-profile/src/author-profile.js
- packages/pages/__tests__/shared.base.js
- packages/pages/src/article/article-prop-types.js
- packages/pages/src/article/index.js
- packages/pages/src/author-profile/index.js
- packages/pages/src/section/index.js
- packages/pages/src/topic/index.js
- packages/responsive/__tests__/shared.base.js
- packages/responsive/src/responsive.tsx
- packages/topic/src/topic.js
> fix(TNLT-5484): passes dimensions to article/topic/author pages

- package.json
- Releases various fixes for orientation on android devices
- Removes duplicate label and fixes alignment issues on `CommentLeadAndCartoonSlice` on mobile and tablet.
> chore: release v1.11.10

- packages/utils/src/dimensions-util.js
This was discussed offline with @ChristianGarcia to change the orientation event name from android
> fix: (TNLT-5484) changes orientation event name

- package.json
Changes orientation event name
> chore: release 1.11.11

- package.json
- Releases new tooltip component used for commenting.
> chore: release v1.13.0

- package.json
> chore: Release v1.14.0

- package.json
> chore: release v1.14.1

- package.json
- fix: (TNLT-6029) Adjusts the content inset behaviour on ScrollView
> chore: release v1.14.3

- package.json
- Author byline tooltip feature
> chore: release v1.15.0

- packages/article-comment-tablet/src/article-comment-tablet.js
- packages/article-extras/src/article-extras-content.js
- packages/article-extras/src/article-extras.js
- packages/article-extras/src/article-topics/index.js
- packages/article-skeleton/src/article-skeleton.js
- Fix to a couple of integration issues with tooltips
> fix: Couple of integration issues with tooltips

- package.json
> chore: release v1.15.1

- packages/article-comment-tablet/src/article-comment-tablet.js
- Missing onTooltipPresented callback
> fix: Missing onTooltipPresented callback

- package.json
- Fix `onTooltipPresented` not firing
> chore: release v1.15.3

- package.json
> chore: release 2.0.3

- package.json
- Removes ad variant logic
- Updates RN dependencies to be compatible with XCode 12 (react-native-device-info, react-native-svg, react-native-webview, @react-native-community/netinfo)
> chore: releases 2.1.0

- packages/article-skeleton/__tests__/body-utils.native.js
- packages/article-skeleton/src/body-utils.js
https://nidigitalsolutions.jira.com/browse/TNLT-5829
Made article mpu type dependent on if non-paragraph content found within the first 10 items of an article.
* Single MPU if non-paragraph content found within the threshold
* Double MPU if not
https://user-images.githubusercontent.com/5103512/103775064-71e86600-5025-11eb-8fd3-c78eb498d6fb.mov
> feat: Dynamic article MPU selection

- packages/article-comment-tablet/src/article-left-column/article-left-column.js
- packages/article-error/__tests__/android/__snapshots__/article-error-style.test.js.snap
- packages/article-error/__tests__/ios/__snapshots__/article-error-style.test.js.snap
- packages/article-error/src/article-error.js
- packages/article-image/src/article-image.base.js
- packages/author-profile/src/author-profile-head-image.js
- packages/image/__tests__/android/__snapshots__/modal-image.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/modal-image.ios.test.js.snap
- packages/image/src/lazy-loading-image/lazy-loading-image.js
- packages/image/src/styles/shared.js
- packages/responsive-image/__tests__/__snapshots__/image.test.tsx.snap
- packages/responsive-image/__tests__/image.test.tsx
- packages/responsive-image/src/index.tsx
Reverts newsuk/times-components-native#273
I believe this causing some images not to display
> fix: (TNLT-995) [Revert] Add image placeholders for offline use (iOS)

- package.json
- revert TNLT-995 due to images occasionally not displaying
> chore: release 2.1.1

- package.json
-  chore: refactoring TileImage, remove Tile-af, Tile-aa, 
-  chore: TypeScript, refactors section utils, remove link prop, renames .native.js files to .js 
- feat: adds variant for lead1and1 WIP 
-  feat: (TNLT-6012) Trigger article read
-  feat: (TNLT-3187) Article read indicator 
- fix: (TNLT-649) - Android - functional issues images in gallery
- fix: (TNLT-6168) - Android - display carousel in modal from Lead Asset
- fix: (TNLT-994) AND/IOS Update play button to new design
> chore: release 2.1.2

- package.json
chore release v2.3.0
Commits in this release:
feat: (TNLT-6350) add 2 by 3 image fragment to support2 on leadtwonopicandtwo fragment (#299)
feat: TNLT-6350 Register Slice transform and Lead two no pic and two variant for sport section (#315)
> chore: release v2.3.0

- package.json
Fixes:
TNLT-6524: Hide close button on android for tooltip
TNLT-5966: Migrate drop cap to new approach
TNLT-6532: Opta widget showing error on mobile
TNLT-6564, TNLT-6565: Increase minimum screen width used for styling tablets
> chore: Release v2.3.1

- .eslintrc.js
- packages/article-main-standard/src/article-main-standard.js
> chore: lints unused vars

- packages/interactive-wrapper/__tests__/android/interactive-wrapper.test.js
- packages/interactive-wrapper/src/interactive-wrapper.android.js
- https://nidigitalsolutions.jira.com/browse/TNLT-6613
- Sorry my last fix created an issue where all widgets stopped displaying.
> fix: (TNLT-6613) fix all interactives widget not showing

- package.json
TNLT-6613: Fix all interactives widget not showing
Decoupled styling tablet width from isTablet
> chore: Release V2.3.3

- package.json
- fix: (TNLT-6569) Lead 2 No Pic 2 styling on iPad Pro 12 inch (#337)
- chore: (TNLT-6506/TNLT-6563) New Ad logic (#338)
- feat: (TNLT-6359/TNLT-6292/TNLT-6334) lead magazine slice (#319)
- fix: (TNLT-6352) orientation aware consecutive slices (#336)
> chore: release v2.4.0

- package.json
v3.0.0 release
feat(TNLT-6530): pass article id to tooltip (#324)
> chore: release v3.0.0 tooltip (breaking change)

- package.json
chore: (TNLT-6479) article performance (#343)
feat: improve section performance (#342)
(TNLT-6636 ) Enabled ads on comment based templates and show centered single MPU when 5th para sandwiched by non para content (#345)
> chore: release 3.0.1

- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/src/article-body/article-body-row.js
- packages/article-skeleton/src/styles/article-body/index.android.js
- packages/article-skeleton/src/styles/article-body/index.js
- packages/article-skeleton/src/styles/article-body/shared.js
follow on from #343 
https://nidigitalsolutions.jira.com/browse/TNLT-6479
> chore: (TNLT-6479) refactor inline styles to stylesheet objects

- package.json
chore: (TNLT-6674) ad optimisations (#350)
fix:  : (TNLT-6674) memoize article content (#349)
chore: (TNLT-6479) refactor inline styles to stylesheet objects (#347)
> chore: release 3.0.2

- package.json
fix: (TNLT-6731) fixes link text size in article (#353)
fix: (TNLT-6708) calculates section content height with RN (#352)
fix: (TNLT-6511) scroll through images in order (#344)
> chore: release 3.0.3

- package.json
(TNLT-6397) Article read animation (#355)
(TNLT-6697) Disable comments globally through firebase (#356)
(TNLT-6770) Remoe extra padding on interactives (#359)
Integration of article read with all templates (#358)
(TNLT-6436) Context retention (#357)
> chore: Release v3.1.0

- CODEOWNERS
> chore: Removes c-j-j from CODEOWNERS

- package.json
Releases:
- chore: (BREAKING CHANGE) Update read articles to be event based
> chore: Release v5.0.0

- packages/pages/__tests__/ios/track-section.test.ts
- packages/pages/src/section/track-section.js
- https://nidigitalsolutions.jira.com/browse/TNLT-6824
- This removes tracking of sections from the react-native side as it will be handled natively in ios.
> fix: (TNLT-6824): remove tracking section on ios

- package.json
- fix: (TNLT-6824): remove tracking section on ios
> chore: release v5.0.1

- packages/article-skeleton/src/article-skeleton.js
- packages/article-summary/src/article-summary.js
- packages/edition-slices/__tests__/mocks-tiles.js
- packages/edition-slices/__tests__/mocks.js
- packages/edition-slices/__tests__/shared-components.base.js
- packages/edition-slices/src/tiles/shared/article-summary.tsx
- packages/edition-slices/src/tiles/shared/tile-summary.tsx
- packages/pages/src/section/section.js
- fix orientation change bug where article read status was wiped on orientation change
> fix: (TNLT-6397) Article Read orientation change

- package.json
Release of 
- Bug fix for article read feature on orientation change
- Fix section ads
> chore: Release v5.0.2

- packages/section/src/section.tsx
- fix context retention on section page
> fix: Context retention on section page

- package.json
Releases:
- https://github.com/newsuk/times-components-native/pull/374 fix: Context retention on section page
> chore: release v5.0.3

- package.json
Releases:
- chore: (TNLT-6184) Remove unused email puzzle button 
- feat: (TNLT-6872) Article End Tracking
> chore: Release v5.2.0

- package.json
* (TNLT-7168) Additional Android changes #389
> chore: Release v5.3.0

- packages/article-comments/__tests__/android/__snapshots__/shared-with-style.android.test.js.snap
- packages/article-comments/__tests__/ios/__snapshots__/shared-with-style.ios.test.js.snap
- packages/tooltip/__tests__/android/__snapshots__/shared.test.js.snap
- packages/tooltip/__tests__/ios/__snapshots__/shared.test.js.snap
- packages/tooltip/styles/index.js
- Fixed layout issue with commenting tooltip on mobile when tooltip wasn't not displayed
> fix: Commenting tooltip on mobile

- package.json
Includes:
- fix: Commenting tooltip on mobile
> chore: release v5.3.1

- package.json
- Disable Article end tracking on Android
> chore: release v5.3.2

- package.json
Release includes
- chore: Update CODEOWNERS 
- feat: (TNLT-558) Search
> chore: release v5.4.0

- package.json
Release includes
refactor: Search UI improvements;
fix: single tap on android to open the articles
> chore: release 5.4.1

- ios/Podfile.lock
- package.json
- yarn.lock
Reverted the netInfo library version in order to fix the android build issue
> fix: reverted the netinfo lib version

- CODEOWNERS
-  Add marionoratoRN to codeowners
> chore: Add marionoratoRN to codeowners

- packages/article-summary/__tests__/android/__snapshots__/article-summary-with-style.android.test.js.snap
- packages/article-summary/__tests__/android/__snapshots__/article-summary.android.test.js.snap
- packages/article-summary/__tests__/ios/__snapshots__/article-summary-with-style.ios.test.js.snap
- packages/article-summary/__tests__/ios/__snapshots__/article-summary.ios.test.js.snap
- packages/article-summary/src/article-summary.js
- packages/edition-slices/__tests__/android/__snapshots__/tile-ah.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tile-h.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tile-ah.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tile-h.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std-has-video.android.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std-with-style.android.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std.android-1article.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std.android-2articles.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std.android-3articles.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std.android-no-short-headline.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-1article.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-2articles.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-3articles.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-has-video.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-no-short-headline.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-with-style.ios.test.js.snap
- Fix issue where android app crashes when first article in Comment section
- https://nidigitalsolutions.jira.com/browse/TNLT-7397
https://user-images.githubusercontent.com/1736782/114694169-2f17e780-9d12-11eb-951e-2cb2e6b87913.mov
https://user-images.githubusercontent.com/1736782/114696551-b1a1a680-9d14-11eb-996a-f7e5d83857b8.mov
> fix: Crash issue on android

- packages/tooltip/__tests__/android/__snapshots__/shared.test.js.snap
- packages/tooltip/__tests__/ios/__snapshots__/shared.test.js.snap
- packages/tooltip/styles/index.js
- Fix android crashing after multiple rotations.
> fix: (TNLT-7334) android crashes

- package.json
Release:
fix: (TNLT-7334) android crashes (#406) …
fix: search box focus area (#404) …
chore: update ad network id (#405)
fix: crash issue on android (#402)
chore: add marionoratoRN to codeowners (#403)
> chore: release v5.4.3

- packages/search/__tests__/android/__snapshots__/infinite-hits.test.ts.snap
- packages/search/__tests__/android/__snapshots__/search-list.test.ts.snap
- packages/search/__tests__/ios/__snapshots__/infinite-hits.test.ts.snap
- packages/search/__tests__/ios/__snapshots__/search-list.test.ts.snap
- packages/search/src/search-list/search-list-empty-state.tsx
- packages/search/src/search-list/styles/search-list-empty-state-styles.ts
- packages/search/src/search-list/styles/search-list-item-snippet-styles.ts
This PR fixes the keyboard issue on the empty search screen and some fonts that were not consistent with the design
> fix: TNLT-7403 TNLT-7420 Keyboard on empty search screen + wrong fonts

- packages/article-magazine-comment/src/article-magazine-comment.js
- packages/article-main-comment/src/article-main-comment.js
- Fixes https://nidigitalsolutions.jira.com/browse/TNLT-7472
- `isArticleTablet` was not being passed to `ArticleSkelton` in a couple of templates.
> fix: (TNLT-7472) Pass isArticleTablet in all article templates

- packages/edition-slices/src/tiles/shared/tile-image.tsx
- fixes https://nidigitalsolutions.jira.com/browse/TNLT-7392
> chore: (TNLT-7392) Fixes small video images

- README.md
- update to include patch releases
> chore: update readme with patch release

- packages/ad/__tests__/ios/__snapshots__/ad-with-style.ios.test.js.snap
- packages/ad/src/dom-context.js
- fix issue in ios where videos would play full screen by default.
> fix: (TNLT-6802) full screen video ads

- package.json
Release includes:
- chore: Update codeowners (#419)
- fix: (TNLT-6802) full screen video ads (#416)
- chore: update readme with patch release (#417)
- fix: tiles with video (#418)
- fix: pass isArticleTablet in all article templates (#412)
- NOJIRA: update CODEOWNERS (#413)
> chore: release v5.4.5

- packages/mocks/src/mock-native-modules.js
- packages/pages/src/search/index.tsx
- packages/search/__tests__/android/__snapshots__/search-list.test.ts.snap
- packages/search/__tests__/infinite-hits-shared.tsx
- packages/search/__tests__/ios/__snapshots__/search-list.test.ts.snap
- packages/search/__tests__/search-list-shared.tsx
- packages/search/src/search-list/search-list-empty-state.tsx
- packages/search/src/search-list/search-list.tsx
- packages/search/src/search-results.tsx
- packages/search/src/search.tsx
- packages/search/src/types.ts
- packages/types/index.ts
- packages/types/tracking.ts
> chore: search analytics

- package.json
> chore: minor version bump to 5.5.0

- packages/article-comment-tablet/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
- packages/article-comment-tablet/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-comment-tablet/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
- packages/article-comment-tablet/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-comment-tablet/src/article-comment-tablet.js
> fix: prevent long read flag on letter to editor

- packages/article-in-depth/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-in-depth/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-lead-asset/__tests__/android/__snapshots__/article-lead-asset.test.js.snap
- packages/article-lead-asset/__tests__/ios/__snapshots__/article-lead-asset.test.js.snap
- packages/article-lead-asset/src/article-lead-asset.js
- packages/article-magazine-comment/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-magazine-comment/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-magazine-standard/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-magazine-standard/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-main-standard/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-main-standard/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-main-standard/src/article-header/article-header-standfirst.js
> fix: Identifiers

- .github/PULL_REQUEST_TEMPLATE.md
This change updates the Github pull request template to align with our other React Native project ([Puzzles](https://github.com/newsuk/nuk-tnl-puzzles-app/)).
- Adds a description and screenshots to every PR, helping everyone understand what has changed and why.
- Adds guidelines for PR titles (and the resulting commit message for the squashed commit), helping us improve the commit history on master for our future reference.
- Adds a checklist for tests
N/A (no code changes)
N/A (no code changes)
> chore(NOJIRA): Update pull request template

- package.json
> chore: create patch release

- package.json
- scripts/publish-ios.sh
> chore: Release 9.4.2

- package.json
* conditional links for key moments 
* remove feature flag condition for dynamic bullets
> chore: release 9.6.0

- package.json
TCN release 9.7.7 - includes: 
* [TNLT-9577](https://nidigitalsolutions.jira.com/browse/TNLT-9577) - TCN - conditionally use Android scrollToY bridge feature
> chore: release 9.7.7

- package.json
TCN - RELEASE 9.7.8
includes
* Read / Live refactor --> [https://nidigitalsolutions.jira.com/browse/TNLT-9561](https://nidigitalsolutions.jira.com/browse/TNLT-9561)
> release 9.7.8

- package.json
> release 9.7.9

- package.json
> TCN 9.7.13

- package.json
NO-JIRA
RELEASE 10.0.1 -- AD LIBRARY
> release 10.0.1

- package.json
> chore: release/10.0.2

- package.json
No JIRA ticket, just a version bump
> chore: version bump to 10.0.3

- package.json
TCN 10.0.6 release
Note: needed to skip 10.0.5 due to a git issue
> release 10.0.6

- package.json
- scripts/trigger-android-build.sh
> release 11.0.1

- package.json
TCN release 11.0.4
* update AD Lib url to production
> release 11.0.4

- package.json
Contains: Key Moments fix for Android - removing scrollToY bridge dependency 
TCN Release 11.0.5
> TCN release 11.0.5

- package.json
- packages/article-comment-tablet/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
- packages/article-comment-tablet/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-comment-tablet/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
- packages/article-comment-tablet/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-comment-tablet/src/article-comment-tablet.js
- packages/article-comment-tablet/src/article-left-column/article-left-column.js
- packages/article-comment-tablet/src/styles/index.js
- packages/article-skeleton/__tests__/android/__snapshots__/article-images-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-images-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-scaling.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/src/article-skeleton.js
- packages/article-skeleton/src/styles/shared.js
On landscape tablets, you can now scroll article content by scrolling anywhere on the page - not just on the main column.
Topic links are still clickable.
> Fix(TNLT-8969): comment page scrolling
