newsuk/times-components-native

.circleci/config.yml, scripts/publish-notes.sh
This PR brings `node_modules/` into the `publish_notes` job so we can run the `conventional-github-releaser` command.
=> fix: Publish notes workflow

packages/edition-slices/__tests__/shared-tablet-slices.base.js, packages/edition-slices/edition-slices.showcase.js, packages/edition-slices/src/edition-slices.js, packages/edition-slices/src/slices/index.js, packages/fixture-generator/src/mock-edition.ts, packages/fixture-generator/src/mock-section.ts, packages/fixture-generator/src/mock-slice.ts, packages/front-page/__tests__/__snapshots__/front-renderer.test.js.snap, packages/front-page/front-renderer.js, packages/section/__tests__/android/__snapshots__/section.test.js.snap, packages/section/__tests__/ios/__snapshots__/section.test.js.snap, packages/section/__tests__/shared.js, packages/section/src/section.js
We don't need to render a FlatList for the front page as it's a full-screen slice with no scrolling enabled.
Also reduces paragraph indentation
=> fix(TNLT-3679): Renders FrontSection slice without FlatList.

packages/article-summary/__tests__/shared-with-style.base.js, packages/article-summary/src/article-summary-content.js, packages/edition-slices/__tests__/android/__snapshots__/tile-al-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-d-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-e-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-x-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-y-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-al-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-d-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-e-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-x-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-y-front.test.js.snap, packages/edition-slices/src/tiles/shared/tile-summary.js, packages/edition-slices/src/tiles/tile-al-front/index.js, packages/edition-slices/src/tiles/tile-d-front/index.js, packages/edition-slices/src/tiles/tile-e-front/index.js, packages/edition-slices/src/tiles/tile-x-front/index.js, packages/edition-slices/src/tiles/tile-y-front/index.js, packages/front-page/MeasureContainer.tsx, packages/front-page/__tests__/__snapshots__/front-article-summary-content.test.js.snap, packages/front-page/__tests__/__snapshots__/front-tile-summary.test.js.snap, packages/front-page/__tests__/front-article-summary-content.test.js, packages/front-page/front-article-summary-content/index.tsx, packages/front-page/front-article-summary-content/styles.js, packages/front-page/front-tile-summary.tsx, packages/front-page/styles/index.js
Rather than using the existing WithoutWhitespace which doesn't seem to work very well with the flexible frontpage layout, I created a new simpler version for the front page, which works out the whitespace height available. This also fixed the orientation issues we had, whereby now reorientating the device rerenders the tiles correctly.
**iPad Mini**
**iPad Air 3**
=> fix(TNLT-4256): Fixes text filling issue on front page.

packages/pages/src/article/index.js, packages/pages/src/with-error-boundaries.js
Updated the text for the error boundary (only for articles).
=> feat(TNLT-4283): Update error boundaries text for articles

packages/article-columns/__tests__/measure/__snapshots__/MeasureComponents.test.tsx.snap, packages/article-columns/__tests__/render/__snapshots__/Columns.test.tsx.snap, packages/article-columns/article-columns.showcase.js, packages/edition-slices/edition-front.showcase.js, packages/front-page/__tests__/__snapshots__/front-article-summary-content.test.js.snap, packages/front-page/__tests__/__snapshots__/front-renderer.test.js.snap, packages/front-page/front-renderer.tsx
The `highQuality` text break strategy was causing weird results on android, and was causing random line breaks to appear when rendering columns. Also, we rely on the `onTextLayout` callback providing accurate data on how the text was rendered, and we were seeing line breaks appearing in the wrong place. Setting the text break strategy to `simple` fixed these issues. 
I was only seeing this weird behaviour when rendering justified text AND using `TimesDigitalW04` font family.  
However, setting the text break strategy to `simple` has resulted in text not looking as balanced as it once did. Hopefully, once hyphenation is working on android, we will be able to improve on this.
before:
after:
=> fix: fixes line break issue on android when rendering columns

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap, packages/slice-layout/__tests__/android/__snapshots__/front-l2np2-with-style.ios.test.js.snap, packages/slice-layout/src/templates/frontleadoneandone/styles.android.js, packages/slice-layout/src/templates/frontleadtwoandtwo/styles.android.js
Adds extra padding at the bottom of a front on android to factor in bottom nav height.
BEFORE:
AFTER:
=> fix: fixes front section on android to not flow under navbar.

packages/article-comment-tablet/__tests__/android/__snapshots__/article-tablet.android.test.js.snap, packages/article-comment-tablet/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap, packages/article-comment-tablet/__tests__/mocks.native.js, packages/article-comment-tablet/__tests__/shared-tablet.native.js, packages/article-comment-tablet/src/article-comment-tablet.js, packages/article-comment-tablet/src/styles/index.js
- Added support for lead asset in the comment tablet template but only for articles with the `magazinecomment` templateid to avoid duplicate author images being displayed.
=> fix: (TNLT-4746) Add support for lead asset in tablet comment template

packages/article-image/src/article-image.js
- Fixes Inline image layout with narrow content templates
=> fix: (TNLT-4760) Inline image layout with narrow content

lib/android/xnative/proguard-rules.pro, package.json, packages/article-skeleton/article-skeleton.showcase.js
1. Added a story for the newsletter puff - as it's tricky to test locally (you need to find an article with the puff inside, and then need to ensure you're not subscribed so you can see it)
2. Added a rule to the proguard rules file that is required by the react-native-svg library - I've tested a beta AAR with this change and it seems to work - (solution found here: https://github.com/react-native-community/react-native-svg/issues/1061#issuecomment-517031073) - I assume this proguard change is then merged into the other proguard rules on the android production build.
=> fix(TNLT-4574): prevents android app from crashing when subscribing to red box

packages/article-skeleton/src/article-skeleton.js
- Fix comment tablet template not rendering on android
=> fix: Comment tablet template not rendering on android

packages/styleguide/src/breakpoints/index.js
https://nidigitalsolutions.jira.com/browse/TNLT-4286
Apply wide breakpoint container width on narrow comment articles to wide and above.
iPad Pro (12.3) - Landscape
=> chore: fix comment article widths on huge screens

packages/article-skeleton/__tests__/body-utils.native.js, packages/article-skeleton/src/body-utils.js
Fix to correctly override the slotName of an ad when in the control group
=> fix: control group ad slotName and testgroup

packages/ad/src/utils/ad-init.js
Looks like Google's `setTargeting` requires a `string` value so must have been silently failing. I have converted the value from `number` to a `string` to hopefully fix.
=> fix: Set value passed into setTargeting to a string

packages/article-skeleton/src/article-body/article-body-row.js
https://nidigitalsolutions.jira.com/browse/TNLT-5321
https://nidigitalsolutions.jira.com/browse/TNLT-5479
**Error received when trying to render an article with `keyFacts`.**
Whilst we have a renderer for `keyFacts`, `listElement`, `paragraph`, etc, we do not have one for `unorderedList` which is the immediate child of `keyFacts`. Prior to a recent fix for `unknown` types (https://github.com/newsuk/times-components-native/pull/154/files#diff-e98c49c75867b0d30f3de34899289258R377), all unknown element types would be ignored with the `tree` being returned. This was changed to fix other issues with the specific `unknown` type from TPA. However, the fix broke the handling specifically of `unorderedList`. In order to leave this fix in place, I have created another renderer for `unorderedList` …
=> fix: stories not displaying when keyFacts present

packages/ad/__tests__/android/sponsored-ad.android.test.tsx, packages/ad/__tests__/ios/sponsored-ad.ios.test.tsx, packages/ad/__tests__/sponsored-ad.test.tsx, packages/ad/src/sponsored-ad.tsx, test-setup/jest.android.config.js, test-setup/jest.ios.config.js
https://nidigitalsolutions.jira.com/browse/TNLT-5579
WebView events are handled differently by Android and iOS. This PR fixes the sponsored ads (Dianomi) to handle ad clicks for both platforms.
Also changes the Jest test file pattern for both platforms to allow for `ts` and `tsx` files.
=> fix: Linking out from Dianomi ads within a WebView

packages/edition-slices/__tests__/android/__snapshots__/tile-a-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-b-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-f-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-g-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-h-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-a-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-b-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-f-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-g-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-h-front.test.js.snap, packages/edition-slices/__tests__/tile-a-front/shared-tile-a-front.base.js, packages/edition-slices/__tests__/tile-b-front/shared-tile-b-front.base.js, packages/edition-slices/__tests__/tile-f-front/shared-tile-f-front.base.js, packages/edition-slices/__tests__/tile-g-front/shared-tile-g-front.base.js, packages/edition-slices/__tests__/tile-h-front/shared-tile-h-front.base.js, packages/edition-slices/src/tiles/tile-a-front/index.js, packages/edition-slices/src/tiles/tile-a-front/styles/index.js, packages/edition-slices/src/tiles/tile-b-front/index.js, packages/edition-slices/src/tiles/tile-b-front/styles/index.js, packages/edition-slices/src/tiles/tile-f-front/index.js, packages/edition-slices/src/tiles/tile-f-front/styles/index.js, packages/edition-slices/src/tiles/tile-g-front/index.js, packages/edition-slices/src/tiles/tile-g-front/styles/index.js, packages/edition-slices/src/tiles/tile-h-front/index.js, packages/edition-slices/src/tiles/tile-h-front/styles/index.js, packages/styleguide/__tests__/breakpoints/index.test.js, packages/styleguide/src/breakpoints/index.js
- https://nidigitalsolutions.jira.com/browse/TNLT-5530
- Adds ability to add ratio refinement to style config object used to get style by device size.
- Makes sure 834px portrait iPad and iPro are as per zeplin designs.
=> feat: (TNLT-5530) Add ratio refinement for getting style by device size

packages/edition-slices/src/edition-slices.js, packages/edition-slices/src/slices/frontleadone/index.js, packages/edition-slices/src/slices/frontleadoneandone/index.js, packages/edition-slices/src/slices/frontleadtwo/index.js, packages/edition-slices/src/tiles/shared/tile-link.js, packages/fixture-generator/src/types.ts, packages/in-todays-edition/in-todays-edition.tsx, packages/in-todays-edition/item.tsx, packages/pages/src/section/section.js, packages/provider-queries/src/section_fragment.graphql, packages/section/__tests__/android/__snapshots__/section-tracking.test.js.snap, packages/section/__tests__/ios/__snapshots__/section-tracking.test.js.snap, packages/section/src/section.js, packages/section/src/slice.js
- Add `InTheNewsSlice` to front page query
- Fix some incorrect image crops in query
- on section page refactor `onArticlePress` to only send `id` as agreed with Native devs
- on section page refactor `onLinkPress` to only send `url` as agreed with Native devs
=> feat: (TNLT-5500) Integrate fronts

packages/in-todays-edition/__tests__/android/__snapshots__/shared.test.js.snap, packages/in-todays-edition/__tests__/ios/__snapshots__/shared.test.js.snap, packages/in-todays-edition/styles/index.js
- Remove unnecessary padding Right on ITE item in landscape.
=> fix: ITE item padding issue

scripts/fetch-fonts.js
- To de-couple from render we are now using an s3 bucket with all the fonts needed
- Removed web only fonts from config
- Add `GillSansMTStd-Bold`
=> chore: update font paths to use s3 bucket

packages/in-todays-edition/item.tsx, packages/pages/src/section/section.js
- Send a 2nd parameter to `onArticlePressBridge` on secton page to identify that the pressed article link is a puff link for back button functionality.
=> feat: Send extra param for native to identify puff links

packages/edition-slices/__tests__/android/__snapshots__/tile-a-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-f-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-h-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-a-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-f-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-h-front.test.js.snap, packages/edition-slices/src/tiles/tile-a-front/index.js, packages/edition-slices/src/tiles/tile-a-front/styles/index.js, packages/edition-slices/src/tiles/tile-f-front/index.js, packages/edition-slices/src/tiles/tile-f-front/styles/index.js, packages/edition-slices/src/tiles/tile-h-front/index.js, packages/edition-slices/src/tiles/tile-h-front/styles/index.js, packages/front-page/__tests__/front-tile-summary.test.js, packages/front-page/__tests__/get-front-tile-config.test.ts, packages/front-page/front-tile-summary.tsx, packages/front-page/utils/get-front-tile-config.ts
=> fix: Adds correct margins to headlines and optional straplines

packages/edition-slices/__tests__/android/__snapshots__/tile-a-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-b-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-f-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-h-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-a-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-b-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-f-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-h-front.test.js.snap, packages/edition-slices/src/tiles/tile-a-front/index.js, packages/edition-slices/src/tiles/tile-a-front/styles/index.js, packages/edition-slices/src/tiles/tile-b-front/index.js, packages/edition-slices/src/tiles/tile-b-front/styles/index.js, packages/edition-slices/src/tiles/tile-f-front/index.js, packages/edition-slices/src/tiles/tile-f-front/styles/index.js, packages/edition-slices/src/tiles/tile-h-front/index.js, packages/front-page/__tests__/__snapshots__/front-article-summary-content.test.js.snap, packages/front-page/__tests__/__snapshots__/front-tile-summary.test.js.snap, packages/front-page/__tests__/front-article-summary-content.test.js, packages/front-page/__tests__/front-tile-summary.test.js, packages/front-page/__tests__/transform-content-for-front.test.ts, packages/front-page/front-article-summary-content/index.tsx, packages/front-page/front-tile-summary.tsx, packages/front-page/utils/transform-content-for-front.ts
This PR changes the front logic to only hyphenate justified content. 
Furthermore, previously we were only left aligning text in the support tile when it was a maincomment article. As justified content looks bad in a narrow column, we're now always left-aligning text in the support tile.
Also - I fixed the summary text size on the first lead one and one tile in landscape, as it didn't match the support tile.
=> fix: Only hyphenates justified content

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-g-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-g-front.test.js.snap, packages/edition-slices/src/tiles/tile-g-front/index.js, packages/edition-slices/src/tiles/tile-g-front/styles/index.js, packages/slice-layout/__tests__/android/__snapshots__/front-l2.android.test.js.snap, packages/slice-layout/__tests__/ios/__snapshots__/front-l2.ios.test.js.snap, packages/slice-layout/src/templates/frontleadtwo/styles.js
- Fix for https://nidigitalsolutions.jira.com/browse/TNLT-5669
- Make `LeadTwoFront` Slice have same divider colour as other front slices
=> feat: (TNLT-5669) Absolutely position tile g headline

packages/edition-slices/__tests__/android/__snapshots__/tile-g-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-h-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-g-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-h-front.test.js.snap, packages/edition-slices/src/tiles/tile-g-front/index.js, packages/edition-slices/src/tiles/tile-g-front/styles/index.js, packages/edition-slices/src/tiles/tile-h-front/styles/index.js
**iPad 11: Lead Two** 
Changed headline in tile 2 from 30px to 32px on portrait
Changed padding in tile 2 from 5px to 10px on landscape
**iPad mini (and iPad air): Lead Two**
Changed headline in tile 1
=> fix(TNLT-5659): headline text changes on fronts

package.json
- Fix for too much teaser text showing on Tile G Front
- Only show ITE CTA in landscape
=> chore: release v1.11.4

packages/edition-slices/__tests__/android/__snapshots__/tile-g-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-g-front.test.js.snap, packages/edition-slices/src/tiles/tile-g-front/styles/index.js, packages/front-page/__tests__/__snapshots__/front-tile-summary.test.js.snap, packages/front-page/front-tile-summary.tsx
For the larger iPads, we were aligning text to the bottom of the tile due to the absolute positioning that we introduced.
To fix this, we're assigning the minHeight of this container to be the height that is available. Also, I've set the marginBottom of the lead image to 0, and instead am setting paddingTop on the summary container to ensure there's always the right padding between image and headline.
=> fix: Aligns tile summary content to top of tile

packages/edition-slices/__tests__/android/__snapshots__/tile-f-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-f-front.test.js.snap, packages/edition-slices/src/tiles/tile-f-front/index.js
- Add summary text to tile f front in landscape, which displays only if headline is short and there is no standfirst
=> fix: Add summary text to tile f front in landscape

packages/edition-slices/__tests__/android/__snapshots__/tile-a-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-a-front.test.js.snap, packages/edition-slices/src/tiles/tile-a-front/index.js, packages/edition-slices/src/tiles/tile-a-front/styles/index.js
=> fix: fixes 3-deck headline on lead1and1

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-a-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-b-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-h-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-a-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-b-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-h-front.test.js.snap, packages/edition-slices/src/tiles/tile-a-front/styles/index.js, packages/edition-slices/src/tiles/tile-b-front/styles/index.js, packages/edition-slices/src/tiles/tile-h-front/styles/index.js, packages/slice-layout/__tests__/android/__snapshots__/front-l1and1.android.test.js.snap, packages/slice-layout/__tests__/ios/__snapshots__/front-l1and1.ios.test.js.snap, packages/slice-layout/src/templates/frontleadoneandone/styles.js
**Lead one and one - landscape - before:**
**Lead one and one after - landscape - after:**
___
**Lead one and one - portrait - before:**
**Lead one and one after - portrait - after:**
Also removed paddingBottom from lead 2 lead tile (tile h front) - as it's not necessary
=> fix(TNLT-5659): corrects alignment on frontlead1and1/frontlead2

packages/edition-slices/__tests__/android/__snapshots__/tile-f-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-f-front.test.js.snap, packages/edition-slices/src/tiles/tile-f-front/index.js, packages/edition-slices/src/tiles/tile-f-front/styles/index.js
- set col count to 3 on both orientations
- absolutely position headline
=> fix: Three deck headline and col count

packages/article-columns/__tests__/utils/chunkContentIntoColumns.test.tsx, packages/article-columns/utils/chunkContentIntoColumns.ts
**Problem**
We have sometimes seen extra characters appear underneath the article columns. This occurs when the first paragraph takes up the entire first column. When this happens, we were actually rendering an empty paragraph at the end of column 1, and also wasn't starting column 2 with a tab. 
Before splitting a paragraph across two columns, we were first checking if there is **any** room in column 1 for any more content. If there was no room - then we just added the whole paragraph to column 2. However, sometimes there is some room in column 1 (i.e. around 8px due to presence of byline), but not enough for a full line - which was causing the empty paragraph to be rendered in column 1 instead.
**Solution**
Before we attempt to split a paragraph across two columns, we now check if there …
=> fix(TNLT-5722): removes extra chars on columns

packages/front-page/__tests__/__snapshots__/front-article-summary-content.test.js.snap, packages/front-page/__tests__/__snapshots__/front-tile-summary.test.js.snap, packages/front-page/__tests__/front-article-summary-content.test.js, packages/front-page/front-article-summary-content/index.tsx, packages/front-page/front-page.showcase.js, packages/front-page/front-tile-summary.tsx
**Problem**
When rendering a front tile, we were previously measuring how much space is available twice. Firstly, we measured if we can fit headline+strapline+byline+content. Secondly, we measured how much room is available for columns - so we can chunk the content as required.
As we are now absolutely positioning the tile summary to allow it to grow, we're seeing issues with the second measuring phase being done in an absolutely positioned view. The measured heights are coming back all wrong - which is why we're seeing this large column being rendered.
**Solution**
We don't really need the second measuring step. We can use the info captured from the first step, and infer how much space is available for teaser text. This fixes the issue on lead1 landscape.
=> fix: fixes columns on lead1 landscape

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap, packages/in-todays-edition/__tests__/android/__snapshots__/shared.test.js.snap, packages/in-todays-edition/__tests__/ios/__snapshots__/shared.test.js.snap, packages/in-todays-edition/styles/index.js, packages/slice-layout/src/templates/frontleadtwo/styles.js, packages/styleguide/src/colours/functional.js
- https://nidigitalsolutions.jira.com/browse/TNLT-5724
- Mainly padding and font tweaks to the ITE component in portrait
- Make heading of ITE component bold
- More margin above the lead2 slice.
=> chore: (TNLT-5724) Various front layout tweaks

packages/ad/__tests__/inline-ad/measure/__snapshots__/MeasureInlineComponents.test.tsx.snap, packages/ad/src/inline-ad/index.tsx, packages/ad/src/inline-ad/utils/chunkInlineContent.ts, packages/article-paragraph/src/article-paragraph.js, packages/article-paragraph/src/index.js, packages/article-paragraph/src/styles/shared.js, packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
Quirky issue when inline text of an inline ad is only one long paragraph. Always adds the paragraph bottom margin even when not required (as a single paragraph is to be split up) which in turn prevents the content from fitting its calculated & desired height.
**Before:**
**After:**
**Before:**
**After:**
**NOTE: This may also fix the bug seen when screen font size increased in device accessibility settings:**
=> fix: singleMPU with a single long split paragraph

package.json
Will include chapter heading fix, which will require iOS to update react-native-webview dep (https://github.com/newsuk/nuk-tnl-app-ios-universal/pull/2175)
=> chore: release 1.12.0

packages/article-skeleton/__tests__/images.base.js, packages/article-skeleton/src/article-body/inline-newsletter-puff.js, packages/article-skeleton/src/article-body/newsletter-puff-button.js, packages/article-skeleton/src/article-body/newsletter-puff-link.js, packages/tracking/src/tracking-context.js
In this PR we fix the `onPress` and `oneView` tracking by adding the `trackingName` to the NewsletterPuff components.
[TNLT-4872](https://nidigitalsolutions.jira.com/browse/TNLT-4872)
PR [#2654](https://github.com/newsuk/times-components/pull/2654) in `times-components`
=> feat(TNLT-4872): Update newsletter puff tracking

packages/article-topics/__tests__/android/__snapshots__/article-topics-with-style.android.test.js.snap, packages/article-topics/__tests__/ios/__snapshots__/article-topics-with-style.ios.test.js.snap, packages/styleguide/src/colours/functional.js, packages/tooltip/__tests__/android/__snapshots__/shared.test.js.snap, packages/tooltip/__tests__/ios/__snapshots__/shared.test.js.snap
- Although the pink was nice, I thought we should revert back to the blue
=> chore: revert back to blue tooltips

packages/article-skeleton/__tests__/body-utils.native.js, packages/article-skeleton/src/body-utils.js
https://nidigitalsolutions.jira.com/browse/TNLT-5869
Ensures that inline adverts are positioned with the n _th_ (provided as `adPosition` in variants) paragraph inlined i.e. ignoring any non paragraph content when counting items.
=> fix: Ad Position

packages/article-skeleton/__tests__/android/__snapshots__/article-images-with-style.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article-tablet.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article-images-with-style.ios.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article-scaling.ios.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap, packages/article-skeleton/src/article-skeleton.js, packages/article-skeleton/src/styles/shared.js, packages/article-topics/__tests__/android/__snapshots__/article-topics-with-style.android.test.js.snap, packages/article-topics/__tests__/ios/__snapshots__/article-topics-with-style.ios.test.js.snap, packages/article-topics/src/article-topic.js
- Fixes issue with content being clipped 
- `overflow-hidden` was introduced in this PR: https://github.com/newsuk/times-components/pull/2437/commits/f14e38786aa84485d49731674b28bbe6641a0f44 but I can't find a problem with removing it
- Also fixes issue with article topic being highlighted even when no tooltip is displayed.
=> fix: Remove overflow hidden on article containers + topic tooltip issue

packages/article-skeleton/__tests__/android/__snapshots__/article-header-with-style.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article-images.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article-header-with-style.ios.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article-images.ios.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap, packages/article-skeleton/src/article-skeleton.js
- Fix for https://nidigitalsolutions.jira.com/browse/TNLT-6029
- Issue is only present on iOS devices not Android
- Adjusts the content inset behaviour on ScrollView. See docs: https://reactnative.dev/docs/scrollview#contentinsetadjustmentbehavior
=> fix: (TNLT-6029) Adjusts the content inset behaviour on ScrollView

package.json
- Fix for `onTooltipPresented` not being passed
=> chore: release v1.15.2

packages/article-byline/src/article-byline-with-links.js, packages/article-comment-tablet/__tests__/android/__snapshots__/article.android.test.js.snap, packages/article-comment-tablet/__tests__/ios/__snapshots__/article.ios.test.js.snap, packages/article-comment-tablet/src/article-left-column/article-left-column.js, packages/article-topics/src/article-topic-prop-types.js, packages/article-topics/src/article-topic.js, packages/article-topics/src/article-topics-prop-types.js, packages/article-topics/src/article-topics.js, packages/tooltip/__tests__/shared.js, packages/tooltip/tooltip.tsx
- The `Viewport` component being used to fire the `onTooltipPresented` callback does not work when not within either a `FlatList`, `ScrollView` or `SectionList` see: https://netcetera.gitbooks.io/skele/content/packages/components/. 
- As the Comment tablet template has a left column that does not use one of these components but is always initially displayed to the user we can fire the `onTooltipPresented` callback straight away in for topics and byline tooltips on this template.
- `Tooltip` component now takes an additional `displayedInView` boolean. (I couldn't think of a nicer name).
=> fix: onTooltipPresented not firing on fixed left-hand column

packages/article-image/__tests__/android/__snapshots__/article-image-with-style.android.test.js.snap, packages/article-image/__tests__/ios/__snapshots__/article-image-with-style.ios.test.js.snap, packages/article-in-depth/__tests__/android/__snapshots__/article-tablet.android.test.js.snap, packages/article-in-depth/__tests__/android/__snapshots__/article-with-style.android.test.js.snap, packages/article-in-depth/__tests__/android/__snapshots__/article.android.test.js.snap, packages/article-in-depth/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap, packages/article-in-depth/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap, packages/article-in-depth/__tests__/ios/__snapshots__/article.ios.test.js.snap, packages/styleguide/src/breakpoints/index.shared.js
Seems we have the max tablet width currently set to `1194`. As far as I can tell this is because this is the landscape width for iPad Pro 11. However the iPad Pro 12.9 is `1366`  thus the PR
Before:
After:
=> chore: Fix max tablet width

packages/ad/src/dom-context.js
Fixes an issue on the android mobile apps, whereby we try to inject javascript into a webview that hasn't loaded yet.
```
TypeError: Cannot read property 'injectJavaScript' of undefined, js engine: v8, stack: Object.S.n.inViewport [as onViewportEnter]@587.js:1:2573 O.o._checkViewportEnterOrLeave@596.js:1:1929 O._onViewportChange@596.js:1:1765 <unknown>@595.js:1:3004 Array.forEach@-1 w.M.<computed> [as notifyViewportListeners]@595.js:1:2977 w.f._onViewportChange@594.js:1:1642 Object.f._onScroll [as onScroll]@594.js:1:1466 y.scrollResponderHandleScroll@279.js:1:2281 n._handleScroll@273.js:1:3371
```
=> fix (TNLT-6233): fixes webview issue on android

package.json, packages/article-main-comment/__tests__/android/__snapshots__/article.android.test.js.snap, packages/article-main-comment/__tests__/ios/__snapshots__/article.ios.test.js.snap, packages/article-main-comment/src/article-header/article-header.js, packages/image/src/modal-image/modal-image-prop-types.js, packages/image/src/modal-image/modal-image.js, packages/image/src/styles/shared.js
- https://nidigitalsolutions.jira.com/browse/TNLT-680
- Display author image in the appropriate size on Android
Before:
After:
=> fix: (TNLT-680) Android - author image appearing in small in modal in

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-a-front.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tile-g-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-a-front.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tile-g-front.test.js.snap, packages/edition-slices/src/tiles/tile-a-front/styles/index.js, packages/edition-slices/src/tiles/tile-g-front/styles/index.js, packages/front-page/__tests__/get-front-tile-config.test.ts, packages/front-page/utils/get-front-tile-config.ts, packages/slice-layout/__tests__/android/__snapshots__/front-l2-with-style.android.test.js.snap, packages/slice-layout/__tests__/android/__snapshots__/front-l2.android.test.js.snap, packages/slice-layout/__tests__/ios/__snapshots__/front-l2-with-style.ios.test.js.snap, packages/slice-layout/__tests__/ios/__snapshots__/front-l2.ios.test.js.snap, packages/slice-layout/src/templates/frontleadtwo/styles.js
https://nidigitalsolutions.jira.com/browse/TNLT-6347
Previously, our front tiles rendered the following in order of priority, and anything that doesn't fit simply was removed from the tile `headline/strapline (if present) + byline + content`
This exposed an issue with the front lead2 when the design changed - whereby we were rendering headline+byline, and then with a large space underneath as there's not enough room for content. To better fill the tile in this context, it's better to render headline+content. So the new rules are as follows:
1. If there is not enough room for headline+byline+content, but there is room for headline+content, then we show headline+content
2. If there is not enough room for headline+byline+content, and there’s only room for headline+byline, then we show …
=> fix(TNLT-6347): changes front lead2 portrait grid

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap, packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap, packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap, packages/edition-slices/__tests__/shared-tablet-slices.base.js, packages/edition-slices/src/slices/secondaryfour/index.js, packages/fixture-generator/src/mock-slice.ts, packages/section/__tests__/unit/__snapshots__/prepareSlicesForRender.test.ts.snap, packages/section/__tests__/unit/consecutiveItemsFlagger.test.ts, packages/section/src/utils/consecutiveItemsFlagger.ts, packages/types/domain-types.ts
This PR ensures that a secondary-four slice displays right-aligned images after they follow a slice with left-aligned images.
There were a few issues with the previous implementation which are now fixed: 
1. We weren't alternating the image alignment from left-right-left and so on. We were only doing left-right-right-etc
2. When we were flipping a secondary-four slice to be right-aligned, the articles were also being flipped, which isn't correct. The articles need to appear in the same order in the slice from left-to-right but have a different display.
https://nidigitalsolutions.jira.com/browse/TNLT-6336
https://nidigitalsolutions.jira.com/browse/TNLT-6352
=> feat: (TNLT-6336/TNLT-6352) secondary-four right-aligned variants (tablet only)

packages/article-summary/src/article-summary-content.js, packages/edition-slices/__tests__/shared-components.base.js, packages/edition-slices/__tests__/shared-tile-utils.js, packages/edition-slices/src/tiles/shared/tile-link.tsx, test-setup/setup-jest.js
This PR fixes a few issues showing in the unit test output.
To fix this particular issue (found solution here https://github.com/facebook/jest/issues/6434) - I've had to have all tile tests use `jest.useFakeTimers()` - as the RN Animated logic was causing tests to not stop gracefully.
```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.
94 |       {labelProps ? <ArticleSummaryLabel {...labelProps} /> : null}
95 |       {isOpinionByline && byline}
> 96 |       {headline}
|        ^
97 |       {strapline}
98 |       {flags}
99 |       {content}
at easeInOut (node_modules/react-native/Libraries/Animated/src/animations/TimingAnimation.js:36:18)
at new TimingAnimation (node_modules/react-native/Libraries/Animated/src/animations/TimingAnimation.js: …
```
=> chore: fixes some unit test warnings

package.json
- feat: (TNLT-6336/TNLT-6352) secondary-four right-aligned variants (tablet only)
- fix: (TNLT-994) play icon showing below image
- fix: (TNLT-6347): changes front lead2 portrait grid
=> chore: release 2.2.0

packages/edition-slices/src/edition-slices.js, packages/section/__tests__/android/__snapshots__/section.test.js.snap, packages/section/__tests__/ios/__snapshots__/section.test.js.snap, packages/section/src/section.tsx, packages/section/src/slice.js
Basically we were previously just using `getDimensions` directly which doesn't update on orientation change so `isTablet` was only calculated once on first render. Now it updates correctly.
=> fix: Fixed sections slices to respect dimension changes on orientation change

packages/section/__tests__/unit/consecutiveItemsFlagger.test.ts, packages/section/__tests__/unit/prepareSlicesForRender.test.ts, packages/section/src/section.tsx, packages/section/src/utils/consecutiveItemsFlagger.ts, packages/section/src/utils/prepareSlicesForRender.ts
https://nidigitalsolutions.jira.com/browse/TNLT-6352
When a secondary-4 follows a lead-one-and-one, the images are now being flipped on the secondary-4 to right-align the images. As the lead-one-and-one has right-aligned images on landscape, we only want to flip the secondary-4 on portrait.
=> fix: (TNLT-6352) orientation aware consecutive slices

packages/ad/src/utils/generate-config.js, packages/ad/src/utils/sizes.js, packages/article-skeleton/__tests__/body-utils/setup-ad.js, packages/article-skeleton/src/article-body/article-body-row.js, packages/article-skeleton/src/body-utils/setupAd.js
https://nidigitalsolutions.jira.com/browse/TNLT-6506
https://nidigitalsolutions.jira.com/browse/TNLT-6563
* Enables adverts on In Depth and Magazine Standard templates.
* Implements the following rules/logic to determine when and what type of advert to display:
* If an article has less than 6 paragraphs of text then do not show any advert
* If an article has 6 or 7 paragraphs of text then show a single mpu ad aligned the start of the 5th paragraph
* If an article has 8 or more paragraphs of text, but also includes inline images/interactives in the first 10 items then show a single mpu
* If an article has 8 or more paragraphs of text but does not include any inline images/interactives in the first 10 items then show a double mpu
* If an article has an image/interactive directly above and …
=> chore: (TNLT-6506/TNLT-6563) New Ad logic

packages/ad/__tests__/ad.shared.js, packages/ad/__tests__/android/__snapshots__/ad.android.test.js.snap, packages/ad/__tests__/ios/__snapshots__/ad.ios.test.js.snap, packages/ad/src/ad.js, packages/article-skeleton/__tests__/body-utils/setup-ad.js, packages/article-skeleton/src/article-body/article-body-row.js, packages/article-skeleton/src/body-utils/setupAd.js
https://nidigitalsolutions.jira.com/browse/TNLT-6636
* Enables ads on both maincomment and magazinecomment templates
* Follows existing ad logic except for showing a centred single MPU when 5th para sandwiched by non para content.
Comment article with ad:
Magazine Comment article with ad:
Comment article with sandwiched 5th paragraph (Note this is a known issue with what is classed as non-paragraph content):
=> feat: (TNLT-6636) Enabled ads on comment based templates

packages/edition-slices/src/slices/commentleadandcartoon/index.js, packages/edition-slices/src/slices/dailyregisterleadfour/index.js, packages/edition-slices/src/slices/leaders/index.js, packages/edition-slices/src/slices/leadoneandfour/index.js, packages/edition-slices/src/slices/leadoneandone/index.js, packages/edition-slices/src/slices/leadonefullwidth/index.js, packages/edition-slices/src/slices/leadtwonopicandtwo/index.js, packages/edition-slices/src/slices/leadtwonopicandtwovariant2/index.js, packages/edition-slices/src/slices/listtwoandsixnopic/index.js, packages/edition-slices/src/slices/puzzle/index.js, packages/edition-slices/src/slices/secondaryfour/index.js, packages/edition-slices/src/slices/secondaryone/index.js, packages/edition-slices/src/slices/secondaryoneandcolumnist/index.js, packages/edition-slices/src/slices/secondaryoneandfour/index.js, packages/edition-slices/src/slices/secondarytwoandtwo/index.js, packages/edition-slices/src/slices/secondarytwonopicandtwo/index.js, packages/edition-slices/src/slices/standard/index.js, packages/section/__tests__/android/__snapshots__/section.test.js.snap, packages/section/__tests__/ios/__snapshots__/section-tracking.test.js.snap, packages/section/__tests__/ios/__snapshots__/section.test.js.snap, packages/section/__tests__/shared-tracking.js, packages/section/src/section.tsx
1. Slices are currently re-rendering many times more than is needed. I converted all slices to PureComponent's, which stops the re-rendering 
2. The section flatlist doesn't need to only render 2 or 5 slices at a time. All the data is loaded into the app, and can be rendered all at once. This results in a better scrolling experience - and I didn't notice a massive jump in RAM when doing this.
On master, if I scroll down on a section, I can see the JS thread struggling to stay at 60fps and often dropping massively to 10/20fps. With this change, the JS thread stays at 60fps most of the time and hardly drops to the extent seen on master. 
There is still an issue with the UI thread whilst scrolling that I cannot figure out what is causing this.
=> feat: improve section performance

packages/article-skeleton/src/article-skeleton.js
Part of https://nidigitalsolutions.jira.com/browse/TNLT-6674
Whenever we render the article AST, it appears that the entire component tree is being destroyed and recreated. This is causing issues like ad's re-rendering and showing a different image whilst the user is scrolling.
Also, whenever an article was marked as read, that state change was causing a re-render of the article.
1. Extract the components that renders the article AST into its own component such that it's not impacted by the `hasBeenRead` state changes.
2. Memoise this new wrapped component to prevent unnecessary re-renders.
=> fix: (TNLT-6674) memoize article content

packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap, packages/article-skeleton/src/article-body/article-body-row.js, packages/article-skeleton/src/styles/article-body/shared.js
https://nidigitalsolutions.jira.com/browse/TNLT-6731
=> fix: (TNLT-6731) fixes link text size in article

packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap, packages/article-skeleton/src/styles/article-body/shared.js
- https://nidigitalsolutions.jira.com/browse/TNLT-6770
- Remove extra padding on interactives on mobile
**Before**
**After**
**Tablet**
=> fix: (TNLT-6770) Remove extra padding on interactives

package.json
* (TNLT-6786) BREAKING CHANGE - Updates ReactNative to 0.63.4 and reverts Android Dimensions temporary fix.
Note this will require updating both iOS and Android to build:
https://github.com/newsuk/nuk-tnl-app-android-universal/pull/1191
https://github.com/newsuk/nuk-tnl-app-ios-universal/pull/2345
=> chore: Release v4.0.0 - BREAKING CHANGE

package.json, packages/ad/src/dom-context.js, packages/section/src/section.tsx
Adverts are not displaying on sections on Android
Viewport Aware View that helps to lazy load the ads needs to be contained by a `Viewport.Tracker` to work. Without that, `onViewportEnter` never fires and ads are never loaded.
=> fix: (TNLT-6840) Ads not displaying in section screens on Android

packages/article-skeleton/src/article-body/article-body-row.js, packages/article-skeleton/src/styles/article-body/shared.js
- Improve the layout of the interactives of type `in-article-puff`
- https://nidigitalsolutions.jira.com/browse/TNLT-6846
- There is also work to be done _within the interactive code itself_ which will come at a later date.
=> fix: (TNLT-6846) In article puff interactive on narrow content templates

package.json
Release of 
- fix: (TNLT-6846) In article puff interactive on narrow content templates
=> chore: Release v5.0.4

packages/edition-slices/src/tiles/shared/tile-image.tsx
https://nidigitalsolutions.jira.com/browse/TNLT-7048
* Fixes the landscape layout of the LeadTile image in the SupplementLeadOneAndFourV2 (only used by iOS) when lead asset is a video.
**Before:**
**After:**
=> fix: (TNLT-7048) SupplementLeadOneAndFourV2 Lead Tile image in iOS landscape

package.json
Releases the following :
- feat: (TNLT-6995 ) Mobile tooltips 
- fix: (TNLT-7048) SupplementLeadOneAndFourV2 Lead Tile image in iOS landscape 
- fix: Video label on android devices 
- chore: Make article page scroll view nested scroll enabled 
- fix: (TNLT-6970) Fixes article and section judder when returning app to foreground
=> chore: release v5.1.0

packages/article-skeleton/__tests__/android/__snapshots__/article-end-tracking.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article-header-with-style.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article-images-with-style.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article-images.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article-tablet.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap, packages/article-skeleton/__tests__/article-end-tracking.base.android.js, packages/article-skeleton/src/article-body/article-end-tracking.js
Disable article end tracking for Android until `Viewport.Aware` fixed or replaced.
=> chore: Disable article end tracking for Android

packages/ad/__tests__/android/__snapshots__/ad.android.test.js.snap, packages/ad/__tests__/ios/__snapshots__/ad.ios.test.js.snap, packages/ad/fixtures/article-ad-config.json, packages/ad/src/ad-composer-prop-types.js, packages/article-list/fixtures/article-ad-config.json, packages/topic/fixtures/topic-ad-config.json
- Update ad network id to use the primary network `3048`
=> chore: Update ad network id

packages/search/__tests__/android/__snapshots__/search-bar.test.ts.snap, packages/search/__tests__/ios/__snapshots__/search-bar.test.ts.snap, packages/search/src/search-bar/styles/search-bar-styles.ts
This PR fixes the bug that caused the search box focus area to be too small. Now it is possible to focus on the search box by tapping across the whole text input area.
=> fix: search box focus area

package.json, packages/tooltip/__tests__/android/__snapshots__/shared.test.js.snap, packages/tooltip/__tests__/android/__snapshots__/tooltip.android.test.js.snap, packages/tooltip/__tests__/ios/__snapshots__/shared.test.js.snap, packages/tooltip/styles/index.ts
On this one i've just removed some padding and updated the file to typescript. I'm not sure why the padding was there to begin with.
It was a tricky one to test. Tested on all emulators and a real Samsung android 12 and real android 11 device, where it's most reproduce-able.
We should just see the same even padding on the tooltips. On iOS there looked like there may have been a reason for the 
padding to avoid the close button, but thought my testing it doesn't seem to be an issue.
Before:
After:
=> fix(TNLT-8138): Tooltip text does not fill tooltip due to added padding on Android 12

package.json, scripts/publish-ios.sh
No Jira
release 9.4.0
The branch format release/9.4.0 automatically creates a release version in circle ci
This is to sync the version number back into develop
=> chore: release 9.4.0

package.json
Includes removal of OutStream ad play pause functionality.
=> chore: release 9.5.0

packages/article-skeleton/src/article-skeleton.js, packages/section/src/section.tsx
Reverts how the state is handled in article-skeleton to a previous method.
Regression was found due to how the `useState` hook forces a re-render of the component rather than using the alternative approach.
A full write up of the problems each case causes can be found here - https://nidigitalsolutions.jira.com/browse/TNLT-9332
https://user-images.githubusercontent.com/101340058/169545363-9529d8d0-1465-4962-a43f-be4c60a3c580.mov
=> fix(TNLT-9332): revert article-skeleton state to use static state object

package.json, packages/article-skeleton/src/article-skeleton.js
The hasBeenRead property in article skeleton was simply a variable, which meant it wouldn't persist if the parent re-rendered.
Changing this to a useRef means that it will persist across re-renders. Using useRef as opposed to useState also means that a change to this value on scroll is recognised within the setTimeout (the 6 second delayed trigger for setting hasRead), meaning that we avoid duplicate events.
It wasn't necessary, but I also memoised `setLayoutRef` and `scrollToRef` functions as they were causing unnecessary re-renders of the child memoised article.
=> feat: (TNLT-9357) improve article read state mgmt & performance

packages/article/src/article.js
Rotating the device with an article inline image open created a red screen error (attached) in dev mode, and exited the image viewer (to return to the article) in non-dev mode.
I memoised the assignment of imageIndex so that it does not unnecessarily run multiple times
=> fix(TNLT-9402): inline images are getting closed automatically and redirecting back to the article page

packages/article-summary/src/article-summary.js, packages/edition-slices/src/configured-tiles/tile-col-standard/index.tsx, packages/edition-slices/src/tiles/shared/article-summary.tsx, packages/edition-slices/src/tiles/shared/tile-summary.tsx
The opacity of a bullet point in a tile does not come from the tile's parent article read state, but instead from the read state of the article in the bullet itself.
=> feat(TNLT-9671): fix read state opacity for bullets

packages/edition-slices/src/slices/leadoneandone/index.js, packages/edition-slices/src/slices/leadtwonopicandtwo/index.js
Bullets were previously unordered, now they are ordered by their key, ie `'lead1Bullet1', 'lead1Bullet2', 'lead1Bullet3'`
=> fux(TNLT-9703):: bullets ordered by key name

packages/edition-slices/__tests__/article-read-state.base.js, packages/edition-slices/src/tiles/shared/article-summary.tsx, packages/edition-slices/src/tiles/shared/tile-summary.tsx
[TNLT-9716](https://nidigitalsolutions.jira.com/browse/TNLT-9716)
~There is no ticket for this, but~ A request has been made to revert the isRead feature so that it only applies on tablet devices.
=> feat: revert isRead feature to tablet only

packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap, packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap, packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap, packages/article-skeleton/fixtures/mixed-link-article-content.js, packages/markup-forest/src/markup-forest.js
As detailed in the ticket, sometimes link text had blank space at the beginning or end, causing the link underline UI to appear underneath the blank space, making it appear to extend before/after the link text.
This fix trims link text during the rendering process, to avoid this.
=> fix(TNLT-2244): prevent underline extending beyond link text

packages/edition-slices/src/tiles/tile-z/index.js
Passing down missing onPress prop to tile used in tablet landscape
=> fix(TNLT-9771): adding onpress prop to tileZ for landscape fix

packages/article-topics/__tests__/android/__snapshots__/article-topics-with-style.android.test.js.snap, packages/article-topics/__tests__/ios/__snapshots__/article-topics-with-style.ios.test.js.snap, packages/article-topics/src/article-topic.js
The border for topic labels is now a subtle grey, as opposed to blue.
Looking at past commits, there was a highlighted state and an unhighlighted state, and highlighting functionality was removed, with the highlighted state remaining as the default. I have changed this so the unhighlighted state is the default
=> style(TNLT-9761): change topic border from highlighted to unhighlighted state

packages/inline-content/src/measure/MeasureInlineContent.tsx, packages/pages/src/section/section.js
Chore: Replaced deprecated removeListener, disambiguate keys on list
- [ x ] Unit tests
- [ x ] Tested on iOS simulator
- [ x ] Tested on Android emulator
- [ x ] Tested on Tablet
=> Chore: Replaced deprecated removeListener, disambiguate keys on list, remove memory leaks

.circleci/config.yml, package.json
Restore build command without 'ram-' for android bundle WIP
It should fix https://app.circleci.com/pipelines/github/newsuk/times-components-native/3463/workflows/ecfc1f05-09e3-4403-ad57-ef633eeacb36/jobs/19775
Introduced in https://github.com/newsuk/times-components-native/pull/675
=> Restore build command without 'ram-' for android bundle WIP

package.json
fix: restore bundle for command ios:build-lib:js
- [ x ] Tested on iOS simulator
=> fix: restore bundle for command ios:build-lib:js
